# Generated by Django 3.2.9 on 2021-11-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neuebenutzer',
            old_name='benutzername',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='neuebenutzer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
