# Generated by Django 3.2.9 on 2021-11-12 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20211112_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neuebenutzer',
            old_name='name',
            new_name='benutzername',
        ),
    ]
