# Generated by Django 3.2.9 on 2021-11-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_rename_name_neuebenutzer_benutzername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neuebenutzer',
            old_name='benutzername',
            new_name='username',
        ),
    ]
