# Generated by Django 3.2.9 on 2021-11-12 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_rename_benutzername_neuebenutzer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuebenutzer',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 12, 9, 46, 47, 836913, tzinfo=utc), verbose_name='date joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neuebenutzer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='neuebenutzer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='neuebenutzer',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2021, 11, 12, 9, 47, 50, 204233, tzinfo=utc), verbose_name='last login'),
            preserve_default=False,
        ),
    ]
