# Generated by Django 3.2.8 on 2021-11-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_auto_20211112_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuebenutzer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='neuebenutzer',
            name='user_permissions',
        ),
    ]
