# Generated by Django 3.2.9 on 2021-11-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Inhalt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='Postdatum',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Titel',
        ),
    ]
