# Generated by Django 3.2.9 on 2021-11-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_auto_20211123_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Titel',
            new_name='title',
        ),
    ]
