# Generated by Django 3.2.9 on 2021-11-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0010_rename_titel_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Postdatum',
            new_name='date_posted',
        ),
    ]
