# Generated by Django 3.2.9 on 2021-11-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_auto_20211123_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Titel',
        ),
    ]
