# Generated by Django 3.2.9 on 2021-11-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0012_rename_title_post_titel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Titel',
            new_name='title',
        ),
    ]
