# Generated by Django 3.2.9 on 2021-11-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0014_auto_20211123_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuebenutzer',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
