# Generated by Django 3.2.9 on 2021-11-25 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0016_alter_neuebenutzer_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentare', to='app_1.post')),
            ],
        ),
    ]
