# Generated by Django 3.2.8 on 2021-11-29 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0017_kommentar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnterKommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_1.unterkommentar')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unterkommentar', to='app_1.post')),
            ],
        ),
    ]
