# Generated by Django 3.2.9 on 2021-11-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0018_unterkommentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuebenutzer',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='kommentar',
            name='content',
            field=models.CharField(max_length=250),
        ),
    ]
