# Generated by Django 3.2.9 on 2021-12-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0021_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuebenutzer',
            name='taggs',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
