# Generated by Django 3.2.8 on 2021-12-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0022_neuebenutzer_taggs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
