# Generated by Django 3.2.9 on 2021-12-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0025_neuebenutzer_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuebenutzer',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='neuebenutzer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
