# Generated by Django 3.2.9 on 2021-12-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0028_alter_neuebenutzer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuebenutzer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profilbilder/default.jpg', null=True, upload_to='profilbilder'),
        ),
    ]
