# Generated by Django 3.2.9 on 2021-12-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0029_alter_neuebenutzer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuebenutzer',
            name='taggs',
        ),
    ]
