# Generated by Django 3.2.9 on 2021-12-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0034_alter_post_inhalt'),
        ('app_1', '0034_post_dislikes'),
    ]

    operations = [
    ]
