# Generated by Django 3.2.8 on 2021-12-19 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0035_merge_0034_alter_post_inhalt_0034_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='kommentar',
            name='likes',
            field=models.ManyToManyField(related_name='kommentar_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
