# Generated by Django 3.2.9 on 2022-01-04 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0037_alter_post_inhalt'),
    ]

    operations = [
        migrations.AddField(
            model_name='kommentar',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app_1.kommentar'),
        ),
    ]
