# Generated by Django 3.2.8 on 2022-01-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0038_kommentar_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kommentar',
            name='parent',
        ),
    ]
