# Generated by Django 3.2.8 on 2022-01-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0040_auto_20220106_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unterkommentar',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unterkommentare', to='app_1.kommentar'),
        ),
    ]
