# Generated by Django 3.2.8 on 2022-01-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0041_alter_unterkommentar_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unterkommentar',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unterkommentare', to='app_1.kommentar'),
        ),
    ]
