# Generated by Django 3.2.8 on 2022-01-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0042_alter_unterkommentar_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='unterkommentar',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unterkommentarePost', to='app_1.post'),
        ),
        migrations.AlterField(
            model_name='unterkommentar',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unterkommentareKommentar', to='app_1.kommentar'),
        ),
    ]
