# Generated by Django 3.2.8 on 2022-01-08 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0043_auto_20220107_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='unterkommentar',
            name='likes',
            field=models.ManyToManyField(related_name='unterkommentar_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kommentar',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='kommentar',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unterkommentar',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='unterkommentar',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unterkommentar',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkKommentar', to='app_1.kommentar'),
        ),
        migrations.AlterField(
            model_name='unterkommentar',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkPost', to='app_1.post'),
        ),
    ]
