# Generated by Django 3.2.9 on 2022-01-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0045_auto_20220109_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kommentar',
            old_name='content',
            new_name='kommentar',
        ),
    ]
