# Generated by Django 3.2.9 on 2022-01-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0046_rename_content_kommentar_kommentar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unterkommentar',
            old_name='content',
            new_name='unterkommentar',
        ),
    ]
