# Generated by Django 3.2.9 on 2022-01-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0047_rename_content_unterkommentar_unterkommentar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unterkommentar',
            old_name='parent',
            new_name='überkommentar',
        ),
    ]
