# Generated by Django 3.2.9 on 2022-01-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0049_auto_20220110_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kommentar',
            options={'verbose_name_plural': 'Kommentare'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Beiträge'},
        ),
        migrations.AlterModelOptions(
            name='unterkommentar',
            options={'verbose_name_plural': 'Unterkommentare'},
        ),
    ]
