# Generated by Django 3.2.9 on 2022-01-17 11:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0050_auto_20220110_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kommentar',
            name='kommentar',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='unterkommentar',
            name='unterkommentar',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
